Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-07, with the labels that each got.

#78 images: Adds CoreDNS to dnsutils and jessie-dnsutils
  images/Utils.ps1
  images/dnsutils/Dockerfile
  images/jessie-dnsutils/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#77 images: Adds httpd images
  images/Utils.ps1
  images/httpd/Dockerfile
  images/httpd/httpd.conf
Labels: approved, cncf-cla: yes, lgtm, size/XL

#81 Use june Windows image in staging.
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#82 images: Amends the httpd image
  images/httpd/Dockerfile
  images/httpd/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#83 images: Adds nonroot image
  images/Utils.ps1
  images/nonroot/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#84 images: Updates redis image version
  images/Utils.ps1
Labels: approved, cncf-cla: yes, lgtm, size/XS

#85 Remove sshEnabled from staging template
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#86 Remove extension that installs KB. June image doesn't need it.
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#88 Adding 1min sleep in master extension
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#89 Adding 60sec sleep before while in master extension
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: cncf-cla: yes, size/XS

#90 Use master extension from official repo
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#94 Copy index.html to right path in httpd image
  images/httpd/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#79 Removes image-repo-list extra files
  images/image-repo-list-ws1803
  images/image-repo-list-ws2019
Labels: approved, cncf-cla: yes, lgtm, size/S

#96 Create test-known-issues.md
  test-known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S
