Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-02, with the labels that each got.

#7 Adding documentation for how to build e2e tests
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#11 Update windows-patches extension in aks-engine template
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#9 Updates to readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#12 Change Windows VM to use a 500 IOPs disk instead of 120
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 Updates the taint set in the win-e2e-master-extension
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#15 gb-frontend: Pins apache-httpd and php versions
  images/gb-frontend/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#14 Add custom 1.0.16 Azure CNI URL to template.
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#16 Fixing Azure-CNI 1.0.16 URL
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 Improving build & test steps
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#19 Remove winrm extension and custom cni links
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#20 Correct calculation of CPU usage.
  images/resource-consumer/consume-cpu/consume_cpu_windows.go
  images/resource-consumer/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#22 Remove windows_patches extension
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#21 Remove windows_patches extension
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, size/S

#25 Adds nc.exe to the busybox image
  images/busybox/Dockerfile
  images/hostexec/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#26 Updating to Docker 18.09.2 and enabling OpenSSH
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#24 Add build script for windows binaries
  build/build-windows-k8s.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#27 images: Adds retry for Resolve-DnsName
  images/gb-frontend/run.ps1
  images/gb-redisslave/run.ps1
Labels: approved, cncf-cla: yes, lgtm, size/M
