Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-06, with the labels that each got.

#70 Disable KubeletPodResources feature.
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Image updates (agnhost, dnsutils, jessie-dnsutils, nettest, resource-consumer, resource-consumer-controller, webhook)
  images/Utils.ps1
  images/agnhost/Dockerfile
  images/agnhost/agnhost.golnk
  images/nettest/nettest.go
  images/nettest/nettest.golnk
  images/resource-consumer-controller/controller.golnk
Labels: approved, cncf-cla: yes, lgtm, size/L

#72 Upgrade 1.15 job
  job-templates/kubernetes_release_1_15.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#74 Adding --runtime-config flag
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#75 Update kubernetes_master.json
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#80 Update kubernetes_release_staging.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
