Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-01, with the labels that each got.

#4 Updates image versions
  images/Utils.ps1
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5 Add test image repo lists
  README.md
  images/image-repo-list-ws1803
  images/image-repo-list-ws2019
Labels: approved, cncf-cla: yes, lgtm, size/S

#6 Create kubernetes_release.json
  job-templates/kubernetes_release.json
Labels: approved, cncf-cla: yes, lgtm, size/M
