Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-11, with the labels that each got.

#111 Updates
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Add GMSA extensions
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#112 Adding 1.16 release job template
  job-templates/kubernetes_release_1_16.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#101 Update documentation surrounding aks-engine version and excluded tests.
  aks-engine-version-notes.md
  test-known-issues.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#114 Update kubernetes_release_staging.json orchestrator release
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#115 Update kubernetes_master.json orchestrator release version
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#113 Removing WindowsRunAsUserName feature gate in kubernetes_release_staging job
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#116 Add template for 1.17 job
  job-templates/kubernetes_release_1_17.json
Labels: approved, cncf-cla: yes, lgtm, size/L
