Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-05, with the labels that each got.

#50 images: Adds iperf image
  images/Utils.ps1
  images/iperf/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#60 images: Renames the resource-consumer/controller
  images/Utils.ps1
  images/resource-consumer-controller/Dockerfile
  images/resource-consumer-controller/controller.golnk
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Update extensions & job templates
  extensions/agent_preprovision_extension/v1/node_setup.ps1
  extensions/master_extension/v1/supported-orchestrators.json
  extensions/master_extension/v1/template-link.json
  extensions/master_extension/v1/template.json
  extensions/master_extension/v1/win-e2e-master-extension.sh
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#62 Disable Windows Defender
  extensions/agent_preprovision_extension/v1/node_setup.ps1
Labels: approved, cncf-cla: yes, lgtm, size/XS

#63 Add new job template file for master job
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#64 Update master template to use correct extensions.
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#65 Fix - Remove "name: " from master extension
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#66 testing latest released azure cni
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#67 Add job template for 1.15 branch
  job-templates/kubernetes_release_1_15.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#68 Adding windows patch KB4497934
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#69 Updating master job
  job-templates/kubernetes_master.json
Labels: approved, cncf-cla: yes, lgtm, size/S
