Repository kubernetes-sigs/windows-testing, pull requests merged in 2019-09, with the labels that each got.

#106 Upgrading Azure CNI to 1.0.27
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#92 Add readme for running unit tests on windows node
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#107 Use September Windows image in staging job.
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#98 test: Creates AD Domain for GMSA e2e testing
  extensions/gmsa-dc/README.md
  extensions/gmsa-dc/v1/Promote-DC.ps1
  extensions/gmsa-dc/v1/Setup-gMSA.ps1
  extensions/gmsa-dc/v1/supported-orchestrators.json
  extensions/gmsa-dc/v1/template-link.json
  extensions/gmsa-dc/v1/template.json
  extensions/gmsa-member/README.md
  extensions/gmsa-member/v1/Join-Domain.ps1
  extensions/gmsa-member/v1/supported-orchestrators.json
  extensions/gmsa-member/v1/template-link.json
  extensions/gmsa-member/v1/template.json
Labels: approved, cncf-cla: yes, lgtm, size/XL
