Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-11, with the labels that each got.

#214 image: point test image registries to k8sprow.azurecr.io/kubernetes-e2e-test-images
  images/image-repo-list
  images/image-repo-list-2004
Labels: approved, cncf-cla: yes, lgtm, size/M

#215 Set use managed explicitly
  job-templates/kubernetes_1903_master.json
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_2004_containerd.json
  job-templates/kubernetes_2004_master.json
  job-templates/kubernetes_containerd_1_19.json
  job-templates/kubernetes_containerd_1_19_serial.json
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_serial.json
  job-templates/kubernetes_csi_proxy.json
  job-templates/kubernetes_docker_gpu_master.json
  job-templates/kubernetes_in_tree_volume_plugins.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_1_17_serial.json
  job-templates/kubernetes_release_1_18.json
  job-templates/kubernetes_release_1_18_serial.json
  job-templates/kubernetes_release_1_19.json
  job-templates/kubernetes_release_1_19_serial.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#216 images: replace e2eteam with k8sprow.azurecr.io/kubernetes-e2e-test-images
  gce/prepull-1.14.yaml
  gce/prepull-1.15.yaml
  gce/prepull-1.16.yaml
  gce/prepull-1.17.yaml
  gce/prepull-1.18.yaml
  gce/prepull.yaml
  helpers/hyper-v-mutating-webhook/deployment.yaml
  images/BuildImageManifestLists.ps1
  images/BuildImages.ps1
  images/MirrorUpstreamK8sImgs.ps1
  images/PullImages.ps1
  images/agnhost/Dockerfile
  images/busybox/Dockerfile
  images/cassandra/Dockerfile
  images/dnsutils/Dockerfile
  images/echoserver/Dockerfile
  images/hazelcast-kubernetes/Dockerfile
  images/hostexec/Dockerfile
  images/iperf/Dockerfile
  images/java/Dockerfile
  images/jessie-dnsutils/Dockerfile
  images/kitten/Dockerfile
  images/nautilus/Dockerfile
  images/net/Dockerfile
  images/netexec/Dockerfile
  images/nfs-server/Dockerfile
  images/nginx/Dockerfile
  images/redis/Dockerfile
  images/rethinkdb/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/L

#217 Updating csi-proxy versin to v0.2.2
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_csi_proxy.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#218 disable csi-proxy for GPU cluster so we can get kubelet logs from windows node
  job-templates/kubernetes_docker_gpu_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#219 Adding k8s 1.20 release configs
  job-templates/kubernetes_release_1_20.json
  job-templates/kubernetes_release_1_20_serial.json
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash
