Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-02, with the labels that each got.

#129 Improve kube-system pod check in master extension
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#126 Update prepulled Windows test containers
  gce/prepull-1.14.yaml
  gce/prepull-1.15.yaml
  gce/prepull-1.16.yaml
  gce/prepull-1.17.yaml
  gce/prepull-1.18.yaml
  gce/prepull-head.yaml
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#128 Enabling telemetry for aks-engine
  job-templates/kubernetes_1903_master.json
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#130 Update prepulled containers again
  gce/prepull-1.14.yaml
  gce/prepull-1.15.yaml
  gce/prepull-1.16.yaml
  gce/prepull-1.17.yaml
  gce/prepull-1.18.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#131 Update kubernetes_release_staging.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#132 added INIT_TIMEOUT, wait this amount of time before start running tests
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#125 Add 1909 windows aks-engine template.
  job-templates/kubernetes_1909_master.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#134 Using nodeSelector & Tolerations to prepull test image
  gce/load-test.sh
  gce/loadtest-prepull.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#127 Add logs collector script for aks-engine deployments
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#136 Adds promoterE2eRegistry to image-repo-list
  images/image-repo-list
Labels: approved, cncf-cla: yes, lgtm, size/XS

#135 Redact sensitive content log collection
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#138 Add two more people for aks-engine & Windows
  OWNERS
Labels: approved, cncf-cla: yes, do-not-merge/invalid-owners-file, lgtm, size/XS

#137 Update CNI version and windows image version
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/M
