Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-08, with the labels that each got.

#187 fix: wait for agent nodes to become available before running master extension
  extensions/gmsa-coredns/v1/update-coredns.sh
  extensions/master_extension/v1/win-e2e-master-extension.sh
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#189 Update Hyperv package to 0.8
  job-templates/kubernetes_2004_containerd.json
  job-templates/kubernetes_2004_containerd_hyperv.json
  job-templates/kubernetes_containerd_hyperv.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#190 update to latest aks-windows image versions to fix failing jobs
  job-templates/kubernetes_containerd.json
  job-templates/kubernetes_containerd_hyperv.json
  job-templates/kubernetes_csi_proxy.json
  job-templates/kubernetes_in_tree_volume_plugins.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#193 2004 hyperv testing config updates
  extensions/hyperv-mutating-webhook/v1/configure-hyperv-webhook.sh
  extensions/hyperv-mutating-webhook/v1/template.json
  job-templates/kubernetes_2004_containerd_hyperv.json
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#194 fix: untaint windows ndoes so e2e test passes don't timeout waiting f…
  extensions/hyperv-mutating-webhook/v1/configure-hyperv-webhook.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
