Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-09, with the labels that each got.

#195 Updating aks-engine job templates for hyper-v isolated jobs
  job-templates/kubernetes_2004_containerd_hyperv.json
  job-templates/kubernetes_containerd_hyperv.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#197 Updating hyper-v mutating webhook to account for e2e.test doesn't add node selectors to pods
  helpers/hyper-v-mutating-webhook/deployment.yaml
  helpers/hyper-v-mutating-webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#198 chore: use containerd nightly build for master branch jobs
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_serial.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#199 Adding aks-engine template for docker + GPU test jobs
  job-templates/kubernetes_docker_gpu_master.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#200 fix: set agent count to 2 for 1.17 API model
  job-templates/kubernetes_release_1_17.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#201 upgrade to csi-proxy v0.2.0
  job-templates/kubernetes_csi_proxy.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#202 Updating mutating hyperv webhook to check tags before adding single arch image suffix
  helpers/hyper-v-mutating-webhook/deployment.yaml
  helpers/hyper-v-mutating-webhook/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#204 Update containerd package 0.0.11-1
  job-templates/kubernetes_2004_containerd_hyperv.json
  job-templates/kubernetes_containerd_hyperv.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#205 use Standard_D4s_v3 for windows testing
  job-templates/kubernetes_csi_proxy.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
