Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-04, with the labels that each got.

#161 chore: set the count of master to 3 in windows cluster
  job-templates/kubernetes_storage.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#162 Update OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#163 chore: use csi-proxy v0.1.0
  job-templates/kubernetes_storage.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#164 Revert "chore: set the count of master to 3 in windows cluster"
  OWNERS
  job-templates/kubernetes_storage.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 test: split kubernetes_storage.json into in-tree volume plugins and csi proxy job template
  job-templates/kubernetes_csi_proxy.json
  job-templates/kubernetes_in_tree_volume_plugins.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#166 Update kubernetes_1903_master.json
  job-templates/kubernetes_1903_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#167 added INIT_TIMEOUT
  gce/load-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 fix: fix kubernetes_containerd.json template
  job-templates/kubernetes_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/S
