Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-03, with the labels that each got.

#139 Enable SSH for Windows Nodes.
  job-templates/kubernetes_1903_master.json
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#140 Use kubectl wait instead of sleeps in gce/run-e2e
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#141 fix: explicitly set kubeconfig when using KUBECTL in CSE
  extensions/gmsa-coredns/v1/update-coredns.sh
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Quote splatted args to ginkgo-e2e
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#143 Release 1.18 job template
  job-templates/kubernetes_release_1_14.json
  job-templates/kubernetes_release_1_18.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#145 added hack-run-e2e.sh
  gce/hack-run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#146 switched run-e2e.sh and hack-run-e2e.sh to fix the gce windows e2e tests
  gce/hack-run-e2e.sh
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Update win-ci-logs-collector.sh
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 Update win-ci-logs-collector.sh
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#149 Add an API model for in-tree storage e2e tests on Windows clusters
  job-templates/kubernetes_storage.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#150 Add -T flag to scp
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#153 Install csi-proxy for kubernetes_storage.json
  job-templates/kubernetes_storage.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#152 Adding aks-engine cluster definition for containerd
  job-templates/kubernetes_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#154 Update GCE files for switch to March node images
  gce/load-test.sh
  gce/loadtest-prepull.yaml
  gce/prepull-1.18.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#151 Update Windows Images to March 2020 version
  job-templates/kubernetes_1903_master.json
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release.json
  job-templates/kubernetes_release_1_14.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_1_18.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Describe pods after waiting for prepull
  gce/hack-run-e2e.sh
  gce/load-test.sh
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 Remove httpd:2.4.38-alpine from prepull list
  gce/prepull-1.18.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 Wrap kubectl wait with coreutils timeout
  gce/hack-run-e2e.sh
  gce/load-test.sh
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#155 Add prepull yaml for iis container
  gce/load-test.sh
  gce/loadtest-prepull.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#160 Use azure cni for containerd
  job-templates/kubernetes_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS
