Repository kubernetes-sigs/windows-testing, pull requests merged in 2020-06, with the labels that each got.

#171 ci: use nightly builds of containerd/hcsshim for Azure test passes
  job-templates/kubernetes_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 Add 2004 test config
  job-templates/kubernetes_2004_master.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#173 ci: Install csi-proxy for aks-engine containerd deployments
  job-templates/kubernetes_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#175 Fix documentation for kubetest
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#172 Update Windows hosts to June versions
  hack/update-job-templates.sh
  job-templates/kubernetes_1903_master.json
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_master.json
  job-templates/kubernetes_release.json
  job-templates/kubernetes_release_1_14.json
  job-templates/kubernetes_release_1_15.json
  job-templates/kubernetes_release_1_16.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_1_18.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#176 docs: update kubetest docs in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M
