Repository kubernetes-sigs/windows-testing, pull requests merged in 2021-02, with the labels that each got.

#239 Update vhds to latest versions built
  job-templates/kubernetes_containerd_1_19.json
  job-templates/kubernetes_containerd_1_19_serial.json
  job-templates/kubernetes_containerd_hyperv.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_serial.json
  job-templates/kubernetes_release_1_17.json
  job-templates/kubernetes_release_1_17_serial.json
  job-templates/kubernetes_release_1_18.json
  job-templates/kubernetes_release_1_18_serial.json
  job-templates/kubernetes_release_1_19.json
  job-templates/kubernetes_release_1_19_serial.json
  job-templates/kubernetes_release_1_20.json
  job-templates/kubernetes_release_1_20_serial.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#240 Add prepull from k8s.gcr.io based images.
  gce/prepull-1.21.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/windows, size/M

#242 Replace yliaog with jeremyje for OWNERS in windows-testing/gce/...
  gce/OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS

#244 Support configurable image-repo-list sources in GCE Windows tests.
  gce/hack-run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/windows, size/XS

#243 chore: remove dockerLibraryRegistry from image-repo-list
  images/image-repo-list-2004
  images/image-repo-list-master
Labels: approved, cncf-cla: yes, lgtm, size/XS

#241 Changes gcRegistry to gcEtcdRegistry
  images/image-repo-list-2004
  images/image-repo-list-master
Labels: approved, cncf-cla: yes, lgtm, size/XS

#245 Support configurable image-repo-list sources in GCE Windows tests.
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/windows, size/XS

#247 fix: overwrite --service-account-issuer
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_containerd_hyperv.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_release_staging.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#246 test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1
  gce/loadtest-prepull.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#248 chore: add gcHttpdRegistry in image-repo-list
  images/image-repo-list-2004
  images/image-repo-list-master
Labels: approved, cncf-cla: yes, lgtm, size/XS

#250 docs: add readme to image-repo-list
  README.md
  images/README.md
  images/image-repo-list-2004
Labels: approved, cncf-cla: yes, lgtm, size/M
