Repository kubernetes-sigs/windows-testing, pull requests merged in 2021-03, with the labels that each got.

#251 Update image-repo-list-master
  images/image-repo-list-2004
  images/image-repo-list-master
Labels: approved, cncf-cla: yes, lgtm, size/XS

#254 adding aks-engine template for 20H2 clusters
  job-templates/kubernetes_20h2_master.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#256 Cleans up image repo lists
  images/image-repo-list-2004
  images/image-repo-list-master
  images/image-repo-list-pr
Labels: approved, cncf-cla: yes, lgtm, size/S

#260 Don't rely on the extracted files being on disk
  scripts/win-ci-logs-collector.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#261 use default azure-cni version for 20h2 aks-engine
  job-templates/kubernetes_20h2_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#259 Make image-repo-list-master use e2eprivate gcAuthenticatedRegistry.
  images/image-repo-list-master
Labels: approved, cncf-cla: yes, lgtm, priority/important-soon, sig/windows, size/XS, triage/accepted
