Repository kubernetes-sigs/windows-testing, pull requests merged in 2021-11, with the labels that each got.

#289 Removing configs for 1.19 clusters
  job-templates/kubernetes_containerd_1_19.json
  job-templates/kubernetes_containerd_1_19_serial.json
  job-templates/kubernetes_release_1_19.json
  job-templates/kubernetes_release_1_19_serial.json
Labels: cncf-cla: yes, lgtm, approved, size/L

#290 images: use k8s.gcr.io/e2e-test-images
  images/MirrorUpstreamK8sImgs.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#291 enabling accelerated networking for staging cluster definitions
  job-templates/kubernetes_containerd_nightly.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#292 Revert "enabling accelerated networking for staging cluster definitions"
  job-templates/kubernetes_containerd_nightly.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#293 Revert "Revert "enabling accelerated networking for staging cluster definitions""
  job-templates/kubernetes_containerd_nightly.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#294 Update kubernetes_containerd_master_csi_enabled.json
  job-templates/kubernetes_containerd_master_csi_enabled.json
Labels: cncf-cla: yes, lgtm, approved, size/XS

#295 Update kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_containerd_master_csi_enabled.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#296 update ctrd version to 1.5.8
  job-templates/kubernetes_2004_containerd.json
  job-templates/kubernetes_20h2_master.json
  job-templates/kubernetes_containerd_1_20.json
  job-templates/kubernetes_containerd_1_20_serial.json
  job-templates/kubernetes_containerd_1_21.json
  job-templates/kubernetes_containerd_1_21_serial.json
  job-templates/kubernetes_containerd_1_22.json
  job-templates/kubernetes_containerd_1_22_serial.json
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_csi_enabled.json
  job-templates/kubernetes_containerd_master_serial.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#297 Upgrade Windows Pool VM
  job-templates/kubernetes_release_staging_serial.json
Labels: cncf-cla: yes, lgtm, approved, size/XS

#298 Restart addonmanager
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: sig/windows, cncf-cla: yes, size/S, lgtm, approved

#300 Add Containerd 1.23 templates
  job-templates/kubernetes_containerd_1_23.json
  job-templates/kubernetes_containerd_1_23_serial.json
Labels: cncf-cla: yes, lgtm, approved, size/L
