Repository kubernetes-sigs/windows-testing, pull requests merged in 2021-01, with the labels that each got.

#228 fix: increase wait_for_agent_nodes function timeout to 30m
  extensions/master_extension/v1/win-e2e-master-extension.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#229 cleanup: remove 1.16 API model
  OWNERS
  extensions/master_extension/v1/win-e2e-master-extension.sh
  job-templates/kubernetes_release_1_16.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#230 fix: remove ExecProbeTimeout feature flag for 1903 API model
  job-templates/kubernetes_1903_1_18.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#231 Removing RunAsUserName feature gate from configs targeting master
  job-templates/kubernetes_1909_master.json
  job-templates/kubernetes_2004_master.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 Removing RunAsUserName feature gate from test configs targeting 1.18
  job-templates/kubernetes_1903_1_18.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#234 Update azure cni version to 1.2.2 and containerd to v1.4.3
  job-templates/kubernetes_2004_containerd.json
  job-templates/kubernetes_containerd_1_19.json
  job-templates/kubernetes_containerd_1_19_serial.json
  job-templates/kubernetes_containerd_hyperv.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_serial.json
  job-templates/kubernetes_release_1_19.json
  job-templates/kubernetes_release_1_19_serial.json
  job-templates/kubernetes_release_1_20.json
  job-templates/kubernetes_release_1_20_serial.json
  job-templates/kubernetes_release_staging.json
  job-templates/kubernetes_release_staging_serial.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#236 fix: Use new windows server image to avoid driver daemonset failure
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_csi_proxy.json
  job-templates/kubernetes_in_tree_volume_plugins.json
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#237 Create windows containerd template for running in-tree driver tests
  job-templates/kubernetes_in_tree_containerd.json
Labels: approved, cncf-cla: yes, lgtm, size/M
