Repository kubernetes-sigs/windows-testing, pull requests merged in 2021-06, with the labels that each got.

#270 Update README regarding Windows images
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#272 Add model for hostprocess tests and containerd 1.5
  job-templates/kubernetes_containerd_1_5.json
  job-templates/kubernetes_containerd_master-hostprocess.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/L

#271 Add --disable-log-dump flag to disable k/k log dump path
  gce/hack-run-e2e.sh
  gce/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#273 Update containerd 1.5 to use nightly builds
  job-templates/kubernetes_containerd_1_5.json
Labels: approved, cncf-cla: yes, lgtm, sig/windows, size/XS
