Repository kubernetes-sigs/windows-testing, pull requests merged in 2022-07, with the labels that each got.

#329 Enable presubmit job support in windows unit test scripts
  scripts/ci-k8s-unit-test.sh
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, size/M, lgtm, approved

#330 Fix JOB_TYPE variable name in unit test scripts
  scripts/ci-k8s-unit-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#331 Skip winkernel
  scripts/k8s_unit_windows.ps1
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, size/S, lgtm, approved

#333 create capz workflow with linter enabled
  .github/workflows/capz.yml
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/M, approved, tide/merge-method-squash

#334 Api server requires the setting HPA feature gate
  capz/templates/windows-base.yaml
Labels: cncf-cla: yes, lgtm, approved, size/XS

#335 Small update to make this script work locally
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#336 fix timeout for ginkgo v2
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS
