Repository kubernetes-sigs/windows-testing, pull requests merged in 2022-01, with the labels that each got.

#306 Add feature flag so HPA scale tests pass in 1.23 jobs
  job-templates/kubernetes_containerd_1_23_serial.json
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS

#308 enable azure disk csi driver on 1.23 template
  job-templates/kubernetes_containerd_1_23.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#309 enable azure disk csi driver on Windows cluster
  job-templates/kubernetes_containerd_1_23.json
  job-templates/kubernetes_in_tree_volume_plugins.json
Labels: cncf-cla: yes, size/S, lgtm, approved

#310 Updating containerd to 1.6.0-rc.1 and OS patches
  job-templates/kubernetes_20h2_master.json
  job-templates/kubernetes_containerd_1_20.json
  job-templates/kubernetes_containerd_1_20_serial.json
  job-templates/kubernetes_containerd_1_21.json
  job-templates/kubernetes_containerd_1_21_serial.json
  job-templates/kubernetes_containerd_1_22.json
  job-templates/kubernetes_containerd_1_22_serial.json
  job-templates/kubernetes_containerd_1_23.json
  job-templates/kubernetes_containerd_1_23_serial.json
  job-templates/kubernetes_containerd_csi_proxy.json
  job-templates/kubernetes_containerd_hyperv.json
  job-templates/kubernetes_containerd_master.json
  job-templates/kubernetes_containerd_master_csi_enabled.json
  job-templates/kubernetes_containerd_master_serial.json
  job-templates/kubernetes_containerd_nightly.json
  job-templates/kubernetes_in_tree_containerd.json
Labels: cncf-cla: yes, size/M, lgtm, approved
