Repository kubernetes-sigs/windows-testing, pull requests merged in 2022-12, with the labels that each got.

#348 Update prepare_env_windows.ps1
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#351 Adds --no-progress to choco
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#352 Update az capi extension to v0.1.1
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#353 kube-proxy should be in kube-system
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#355 cleanup: removing aks-engine templates for unsupported cluster configurations
  job-templates/kubernetes_20h2_1_24.json
  job-templates/kubernetes_containerd_1_21.json
  job-templates/kubernetes_containerd_1_21_serial.json
  job-templates/kubernetes_containerd_1_22.json
  job-templates/kubernetes_containerd_1_22_serial.json
  job-templates/kubernetes_release_1_21.json
  job-templates/kubernetes_release_1_21_serial.json
  job-templates/kubernetes_release_1_22.json
Labels: size/XL, cncf-cla: yes, lgtm, approved

#354 Updating Windows VHD used in aks-engine template to include 2022 11B updates
  job-templates/kubernetes_containerd_1_23.json
  job-templates/kubernetes_containerd_1_23_serial.json
  job-templates/kubernetes_containerd_1_24.json
  job-templates/kubernetes_containerd_1_24_csi_enabled.json
  job-templates/kubernetes_release_1_23.json
Labels: cncf-cla: yes, size/S, lgtm, approved
