Repository kubernetes-sigs/windows-testing, pull requests merged in 2022-06, with the labels that each got.

#322 sig-windows custom E2E script and template for cluster api provider azure
  .gitignore
  capz/readme.md
  capz/run-capz-e2e.sh
  capz/templates/windows-base.yaml
  images/image-repo-list-private-registry
Labels: size/XL, cncf-cla: yes, lgtm, approved

#326 Adds claudiubelu to OWNERS
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/XS

#325 Unit test scripts windows
  scripts/ci-k8s-unit-test.sh
  scripts/enable_ssh_windows.ps1
  scripts/k8s_unit_windows.ps1
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/L

#327 Remove healthcheck which is causing issues
  capz/templates/windows-base.yaml
Labels: cncf-cla: yes, size/S, approved
