Repository kubernetes-sigs/windows-testing, pull requests merged in 2022-10, with the labels that each got.

#342 az capi readme and minor updates
  capz/readme.md
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved, tide/merge-method-squash

#346 Default to v0.0.6 of az capi extension
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS

#347 Stop using the beta.kubernetes.io/os
  gce/hack-run-e2e.sh
  gce/run-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS
