Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-02, with the labels that each got.

#358 Update az capi extension to v0.1.2
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#359 Updating az capi extension source to v0.1.3 which supports installing KPNG
  capz/readme.md
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#360 Don't restart kube-proxy ds if configured to run kpng
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#361 Replacing k8s.gcr.io refs with registry.k8s.io in k-sigs/windows-testing
  gce/loadtest-prepull.yaml
  gce/prepull-1.21.yaml
  gce/prepull-1.22.yaml
  gce/prepull-head.yaml
  images/MirrorUpstreamK8sImgs.ps1
Labels: sig/windows, cncf-cla: yes, size/M, lgtm, approved, kind/cleanup
