Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-09, with the labels that each got.

#394 Adds set -x option for unit test script
  scripts/ci-k8s-unit-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#396 Fixing run-lint github workflows
  .github/workflows/capz.yml
  capz/gmsa/configuration/configure.go
Labels: cncf-cla: yes, lgtm, approved, size/XS

#395 Adding logging into replace-containerd.ps1
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#399 Always use same location for kubeconfig
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS

#401 Fixing an issue where run-capz-e2e.sh fails if run from capz directory
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS
