Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-06, with the labels that each got.

#380 Use new calico version in az capi extension
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#381 Add support for node level features
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#383 Fixing issue in run_capz-e2e.sh where log cleanup does not happen after calling ci-build-kubernetes.sh
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, size/S, lgtm, approved
