Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-11, with the labels that each got.

#411 Update calico and containerd default versions
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, tide/merge-method-squash, size/XS

#412 capz: Add env vars for SSH access
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#413 Don't use JOB_NAME when fetching e2e.test in capz-run-e2e.sh
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#415 fixup
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, approved

#404 Updating capz/readme.md
  capz/readme.md
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash

#414 capz/templates: Allow enabling the NodeLogQuery feature
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved
