Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-04, with the labels that each got.

#369 Add ability to skip log collection when running run-capz-e2e.sh locally
  capz/gmsa/configuration/configure.go
  capz/readme.md
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/M, lgtm, approved

#370 Updates the Windows image used for unit tests
  scripts/ci-k8s-unit-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#374 Removing references to WindowsHostProcessContainers feature-gate
  capz/templates/gmsa.yaml
  capz/templates/windows-base.yaml
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS
