Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-01, with the labels that each got.

#349 Builds kubeadm.exe for Windows unit tests
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, size/S, lgtm, approved

#356 Update the pre-kubeadm script to work with < 1.25
  capz/templates/gmsa.yaml
  capz/templates/windows-base.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#357 unit tests: Fixes kubeadm binary build
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS
