Repository kubernetes-sigs/windows-testing, pull requests merged in 2023-07, with the labels that each got.

#384 Adding --debug to az capi SIG Windows jobs
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS

#385 Adding a post-kubeadm action to write EnableLogQuery=true to kubelet config if needed
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: sig/windows, cncf-cla: yes, size/M, lgtm, approved

#386 Stop calling --debug in az capi
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#387 Fixing issue where nodeLogQuery feature was not actually enabled
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#388 Updating control-plane os from Ubuntu 18.04 LTS to 22.04 LTS
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/S, lgtm, approved

#391 Update deps to latest (fixes 390)
  .github/workflows/capz.yml
  capz/gmsa/configuration/configure.go
  capz/gmsa/configuration/go.mod
  capz/gmsa/configuration/go.sum
Labels: sig/windows, size/XXL, cncf-cla: yes, lgtm, approved
