Repository kubernetes-sigs/windows-testing, pull requests merged in 2024-05, with the labels that each got.

#426 Include proxy in Windows unit test runs
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#429 Updating webhook.go to ensure hyperv is applied only to windows pods
  helpers/hyper-v-mutating-webhook/webhook.go
Labels: cncf-cla: yes, ok-to-test, size/XS

#428 skipping linux-speicifc proxy packages during windows unit test execution
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#431 Update gh actions to latest versions
  .github/workflows/capz.yml
  .github/workflows/hyperv-webhook-build.yaml
Labels: cncf-cla: yes, size/S, approved

#432 Update cert-manager deploy for hyperv
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#433 Add flake attempt retry
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#434 Use 2019 as default
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#436 Retry creating cluster with new name and region
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#437 don't repeat output
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS
