Repository kubernetes-sigs/windows-testing, pull requests merged in 2024-06, with the labels that each got.

#435 Parameterize k8s_unit_windows.ps1 to accept a list of packages
  scripts/ci-k8s-unit-test.sh
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, size/S, lgtm, approved

#438 Set registry keys to write process dumps to c:\localdumps
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/shared-image-gallery-ci.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/M, lgtm, approved

#440 unittests: Updates kubeadm build flags
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#442 Add retries properly
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#441 Use calculated template and save it for debugging
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS
