Repository kubernetes-sigs/windows-testing, pull requests merged in 2024-07, with the labels that each got.

#445 Trying to debug why clusters aren't coming up for PR jobs
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#443 Remove storage secret from docs
  capz/readme.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#447 remove file that was removed in capz
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#448 Parse prow creds when token file not present
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#449 Bump go version
  .github/workflows/capz.yml
  capz/gmsa/configuration/go.mod
Labels: cncf-cla: yes, lgtm, approved, size/XS

#451 Must parse values before loading cli
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#452 Drop west Europe do to re-occurring capacity issues
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, approved

#450 Update azure sdk for golang
  capz/gmsa/configuration/configure.go
  capz/gmsa/configuration/go.mod
  capz/gmsa/configuration/go.sum
Labels: cncf-cla: yes, lgtm, approved, size/L

#444 Cncf job migration test
  .gitignore
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved

#455 Update regions for new sub
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#456 update skip until #446 is resolved
  capz/run-capz-e2e.sh
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/XS

#457 Skip DynamicResourceAllocation
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#461 Use federated token to sign-in on new sub
  scripts/ci-k8s-unit-test.sh
Labels: sig/windows, cncf-cla: yes, size/M, lgtm, approved

#459 When moving to new sub, the name of the keyvault changed
  capz/gmsa/ci-gmsa.sh
  capz/gmsa/domain.init.tmpl
  capz/gmsa/readme.md
  capz/gmsa/setup-gmsa.sh
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/L
