Repository kubernetes-sigs/windows-testing, pull requests merged in 2025-03, with the labels that each got.

#485 Skip known failures for windows unit tests
  scripts/ci-k8s-unit-test.sh
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/L

#489 Run prune-junit-xml on junitfiles for windows unit tests
  scripts/k8s_unit_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#491 Skip some beta tests for off-by-default features
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#492 Skipping [Alpha] and [Beta] [Feature:OffByDefault] tests by default for non-serical skip Windows jobs
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#493 Simple refactor - extract the common function part
  scripts/ci-k8s-common.sh
  scripts/ci-k8s-unit-test.sh
Labels: cncf-cla: yes, lgtm, approved, size/L

#495 Use go version from kubekins image when preparing windows node for unit/e2e_node tests
  scripts/ci-k8s-unit-test.sh
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, size/S, lgtm, approved

#484 Add prow job scripts for windows node e2e test
  scripts/ci-k8s-common.sh
  scripts/ci-k8s-e2e-node-test.sh
  scripts/ci-k8s-unit-test.sh
  scripts/k8s_e2e_node_windows.ps1
  scripts/prepare_e2e_node_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/L

#494 Bump Calico version to 3.29
  capz/run-capz-e2e.sh
  capz/templates/calico/values.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved
