Repository kubernetes-sigs/windows-testing, pull requests merged in 2025-02, with the labels that each got.

#478 Updating aks management cluster to 1.31.3
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#479 bump golang version to v1.23.6 for unit tests
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, lgtm, approved, size/XS

#480 Unit tests fixes and parallel
  scripts/ci-k8s-unit-test.sh
  scripts/k8s_unit_windows.ps1
  scripts/prepare_env_windows.ps1
Labels: cncf-cla: yes, size/M, lgtm, approved, tide/merge-method-squash

#481 Enable the cluster worker node ManageIdentity
  capz/run-capz-e2e.sh
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/shared-image-gallery-ci.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
  images/image-repo-list-private-registry-community
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#476 Temp disable the graceful shutdown e2e test case
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS, needs-ok-to-test

#483 skip alpha tests by default for serial slow
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#486 Use older template for running 1.29 jobs
  capz/run-capz-e2e.sh
  capz/templates/1.29/windows-ci.yaml
  capz/templates/1.29/windows-pr.yaml
Labels: sig/windows, cncf-cla: yes, lgtm, approved, size/L

#487 Use correct user identity
  capz/run-capz-e2e.sh
  capz/templates/1.29/windows-ci.yaml
  capz/templates/1.29/windows-pr.yaml
Labels: cncf-cla: yes, lgtm, approved, size/L
