Repository kubernetes-sigs/windows-testing, pull requests merged in 2025-01, with the labels that each got.

#473 Use latest gallery image
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, lgtm, approved, size/XS

#474 copy ssh key to administrator authorized keys
  capz/templates/gmsa-ci.yaml
  capz/templates/gmsa-pr.yaml
  capz/templates/shared-image-gallery-ci.yaml
  capz/templates/windows-base.yaml
  capz/templates/windows-ci.yaml
  capz/templates/windows-pr.yaml
Labels: cncf-cla: yes, size/M, lgtm, ok-to-test, approved

#477 minor fixes
  capz/run-capz-e2e.sh
Labels: cncf-cla: yes, size/S, lgtm, ok-to-test, approved
